### ISSUE TITLE
can i test this pipeline ?

### ISSUE THREAD

**Issue by tws0002** [alexanderrichter/arProject#2]
can i test this pipeline ? 
or you just want to share folder structure?

**Comment by alexanderrichter** [comment]
Thanks for the interest!

Currently it is about sharing the folder structure and building up the wiki.
For everyone to have a good start into a new project.
The official release of the script structure will be at the FMX 2017 (Mai 2017)

Best, Alex

**Comment by tws0002** [comment]
Thanks for your quick reply and sharing.
Next year FMX 2017 you will release the script structure as open source?

Thanks
Desmond

**Comment by alexanderrichter** [comment]
Yes it will be mainly about having a core system which can be expended with addtional scripts and systems like Shotgun. I focus more on the overall system instead of fancy production scripts so it is a good starting point for pipeliner but can also be used by user likewise without anyone in coding.

Will see if I manage to balance it! 🎱

**Comment by tws0002** [comment]
Thanks for sharing all this workflow. I have been waiting ur arpipeline for some time!! I have test ur basic pipeline before!! Just waiting u to release the advance version!!

**Comment by alexanderrichter** [comment]
Thanks! I hope to help creating a better pipeline standard and people like you help with their contribution to maintain a great system for everyone to use.

**Comment by alexanderrichter** [comment]
Yes it will be mainly about having a core system which can be expended with addtional scripts and systems like Shotgun. I focus more on the overall system instead of fancy production scripts so it is a good starting point for pipeliner but can also be used by user likewise without anyone in coding.

Will see if I manage to balance it! 🎱

**Comment by alexanderrichter** [comment]
Thanks!
